name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: release-version
        run: echo "::set-output name=version::${GITHUB_REF:11}"
      - name: Set Release Version
        run: mvn -B versions:set -DnewVersion=${{ steps.release-version.outputs.version }} -DgenerateBackupPoms=false
      - name: Build
        run: mvn -B install
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.release-version.outputs.version }}
          prerelease: contains(github.ref, 'beta')
          files: target/sonarqube-licensecheck-plugin-${{ steps.release-version.outputs.version }}.jar
          fail_on_unmatched_files: true
